# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaultimage: &defaultimage
  docker:
    - image: circleci/node:13.8.0

jobs:

  build:
    <<: *defaultimage
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm_package"
          paths:
            - /src/node_modules
      - run: npm run lint
      - run:
          name: "Fail steps"
          command: echo "Job failed & on fail called"
          when: on_fail

  test:
    <<: *defaultimage
    steps:
      - checkout
      - restore_cache:
          keys: "npm_package"
      - run: npm i
      - run: npm run test

  analyze:
    <<: *defaultimage
    steps:
      - checkout
      - restore_cache:
          keys: "npm_package"
      - run: npm audit

workflows:
  ciflow:
    jobs:
      - build
      - test:
          requires:
          - build
      - analyze:
          requires:
          - test
